### PR TITLE
Make pa-get-default-monitor.sh grep source in use

### PR DESCRIPTION
**Pull request by puzzlemoondev**
Make pa-get-default-monitor.sh grep in-use source instead of first source

### CODE REVIEW

**Comment by Kharacternyk** [comment]
It doesn't work for me. My in-use source is a microphone (I'm not sure whether it's uncommon).

**Comment by puzzlemoondev** [comment]
I use DACs, no microphones. This works for me while the original script does not. I'll find a common solution.

**Comment by Kharacternyk** [comment]
I should clarify that I don't have a microphone plugged-in, but PulseAudio still lists the dedicated to microphones in-JACK on my sound card as the default input. Could it be a misconfiguration of mine?

**Comment by puzzlemoondev** [comment]
It's the same on my laptop. I added a check for fallback monitor if default source is not a monitor.

**Comment by Kharacternyk** [comment]
Thanks!

**Pull request merged**
